#!/usr/bin/env bash

declare -x OWNCLOUD_PROTOCOL
[[ -z "${OWNCLOUD_PROTOCOL}" ]] && OWNCLOUD_PROTOCOL="http"

declare -x OWNCLOUD_DOMAIN
[[ -z "${OWNCLOUD_DOMAIN}" ]] && OWNCLOUD_DOMAIN="localhost"

declare -x OWNCLOUD_DEBUG
[[ -z "${OWNCLOUD_DEBUG}" ]] && OWNCLOUD_DEBUG=""

declare -x OWNCLOUD_SECRET
[[ -z "${OWNCLOUD_SECRET}" ]] && OWNCLOUD_SECRET=""

declare -x OWNCLOUD_CIPHER
[[ -z "${OWNCLOUD_CIPHER}" ]] && OWNCLOUD_CIPHER=""

declare -x OWNCLOUD_PRE_INSTALL_PATH
[[ -z "${OWNCLOUD_PRE_INSTALL_PATH}" ]] && OWNCLOUD_PRE_INSTALL_PATH="/etc/pre_install.d"

declare -x OWNCLOUD_POST_INSTALL_PATH
[[ -z "${OWNCLOUD_POST_INSTALL_PATH}" ]] && OWNCLOUD_POST_INSTALL_PATH="/etc/post_install.d"

declare -x OWNCLOUD_PRE_SERVER_PATH
[[ -z "${OWNCLOUD_PRE_SERVER_PATH}" ]] && OWNCLOUD_PRE_SERVER_PATH="/etc/pre_server.d"

declare -x OWNCLOUD_POST_SERVER_PATH
[[ -z "${OWNCLOUD_POST_SERVER_PATH}" ]] && OWNCLOUD_POST_SERVER_PATH="/etc/post_server.d"

declare -x OWNCLOUD_PRE_CRONJOB_PATH
[[ -z "${OWNCLOUD_PRE_CRONJOB_PATH}" ]] && OWNCLOUD_PRE_CRONJOB_PATH="/etc/pre_cronjob.d"

declare -x OWNCLOUD_POST_CRONJOB_PATH
[[ -z "${OWNCLOUD_POST_CRONJOB_PATH}" ]] && OWNCLOUD_POST_CRONJOB_PATH="/etc/post_cronjob.d"

declare -x OWNCLOUD_MAX_UPLOAD
[[ -z "${OWNCLOUD_MAX_UPLOAD}" ]] && OWNCLOUD_MAX_UPLOAD="20G"

declare -x OWNCLOUD_MAX_EXECUTION_TIME
[[ -z "${OWNCLOUD_MAX_EXECUTION_TIME}" ]] && OWNCLOUD_MAX_EXECUTION_TIME="3600"

declare -x OWNCLOUD_MAX_INPUT_TIME
[[ -z "${OWNCLOUD_MAX_INPUT_TIME}" ]] && OWNCLOUD_MAX_INPUT_TIME="3600"

declare -x OWNCLOUD_SKIP_CHOWN
[[ -z "${OWNCLOUD_SKIP_CHOWN}" ]] && OWNCLOUD_SKIP_CHOWN="false"

declare -x OWNCLOUD_SKIP_CHMOD
[[ -z "${OWNCLOUD_SKIP_CHMOD}" ]] && OWNCLOUD_SKIP_CHMOD="false"

declare -x OWNCLOUD_CROND_ENABLED
[[ -z "${OWNCLOUD_CROND_ENABLED}" ]] && OWNCLOUD_CROND_ENABLED="true"

declare -x OWNCLOUD_FILELOCKING_ENABLED
[[ -z "${OWNCLOUD_FILELOCKING_ENABLED}" ]] && OWNCLOUD_FILELOCKING_ENABLED="${OWNCLOUD_LOCKING_ENABLED:-true}"

declare -x OWNCLOUD_MAINTENANCE
[[ -z "${OWNCLOUD_MAINTENANCE}" ]] && OWNCLOUD_MAINTENANCE="${OWNCLOUD_MAINTENANCE_MODE}"

declare -x OWNCLOUD_SINGLEUSER
[[ -z "${OWNCLOUD_SINGLEUSER}" ]] && OWNCLOUD_SINGLEUSER=""

declare -x OWNCLOUD_BACKGROUND_MODE
[[ -z "${OWNCLOUD_BACKGROUND_MODE}" ]] && OWNCLOUD_BACKGROUND_MODE="cron"

true
