#!/usr/bin/env bash

declare -x OWNCLOUD_LICENSE_KEY
[[ -z "${OWNCLOUD_LICENSE_KEY}" ]] && OWNCLOUD_LICENSE_KEY=""

declare -x OWNCLOUD_LICENSE_CLASS
[[ -z "${OWNCLOUD_LICENSE_CLASS}" ]] && OWNCLOUD_LICENSE_CLASS=""

true
