#!/usr/bin/env bash

declare -x OWNCLOUD_LOG_FILE
[[ -z "${OWNCLOUD_LOG_FILE}" ]] && OWNCLOUD_LOG_FILE="${OWNCLOUD_VOLUME_FILES}/owncloud.log"

declare -x OWNCLOUD_LOG_LEVEL
[[ -z "${OWNCLOUD_LOG_LEVEL}" ]] && OWNCLOUD_LOG_LEVEL="${OWNCLOUD_LOGLEVEL:-2}"

declare -x OWNCLOUD_LOG_DATE_FORMAT
[[ -z "${OWNCLOUD_LOG_DATE_FORMAT}" ]] && OWNCLOUD_LOG_DATE_FORMAT=""

declare -x OWNCLOUD_LOG_TIMEZONE
[[ -z "${OWNCLOUD_LOG_TIMEZONE}" ]] && OWNCLOUD_LOG_TIMEZONE=""

declare -x OWNCLOUD_LOG_ROTATE_SIZE
[[ -z "${OWNCLOUD_LOG_ROTATE_SIZE}" ]] && OWNCLOUD_LOG_ROTATE_SIZE="${OWNCLOUD_LOGSIZE}"

declare -x OWNCLOUD_CRON_LOG
[[ -z "${OWNCLOUD_CRON_LOG}" ]] && OWNCLOUD_CRON_LOG=""

declare -x OWNCLOUD_ACCESSLOG_LOCATION
[[ -z "${OWNCLOUD_ACCESSLOG_LOCATION}" ]] && OWNCLOUD_ACCESSLOG_LOCATION="/dev/stdout"

declare -x OWNCLOUD_ERRORLOG_LOCATION
[[ -z "${OWNCLOUD_ERRORLOG_LOCATION}" ]] && OWNCLOUD_ERRORLOG_LOCATION="/dev/stderr"

true
