#!/usr/bin/env bash

declare -x OWNCLOUD_LOGLEVEL
[[ -z "${OWNCLOUD_LOGLEVEL}" ]] && OWNCLOUD_LOGLEVEL="0"

declare -x OWNCLOUD_MAX_UPLOAD
[[ -z "${OWNCLOUD_MAX_UPLOAD}" ]] && OWNCLOUD_MAX_UPLOAD="20G"

declare -x OWNCLOUD_MAX_EXECUTION_TIME
[[ -z "${OWNCLOUD_MAX_EXECUTION_TIME}" ]] && OWNCLOUD_MAX_EXECUTION_TIME="3600"

declare -x OWNCLOUD_MAX_INPUT_TIME
[[ -z "${OWNCLOUD_MAX_INPUT_TIME}" ]] && OWNCLOUD_MAX_INPUT_TIME="3600"

declare -x OWNCLOUD_SKIP_CHOWN
[[ -z "${OWNCLOUD_SKIP_CHOWN}" ]] && OWNCLOUD_SKIP_CHOWN="false"

true
