#!/usr/bin/env bash

declare -x OWNCLOUD_PRE_INSTALL_PATH
[[ -z "${OWNCLOUD_PRE_INSTALL_PATH}" ]] && OWNCLOUD_PRE_INSTALL_PATH="/etc/pre_install.d"

declare -x OWNCLOUD_POST_INSTALL_PATH
[[ -z "${OWNCLOUD_POST_INSTALL_PATH}" ]] && OWNCLOUD_POST_INSTALL_PATH="/etc/post_install.d"

declare -x OWNCLOUD_PRE_SERVER_PATH
[[ -z "${OWNCLOUD_PRE_SERVER_PATH}" ]] && OWNCLOUD_PRE_SERVER_PATH="/etc/pre_server.d"

declare -x OWNCLOUD_POST_SERVER_PATH
[[ -z "${OWNCLOUD_POST_SERVER_PATH}" ]] && OWNCLOUD_POST_SERVER_PATH="/etc/post_server.d"

declare -x OWNCLOUD_LOGLEVEL
[[ -z "${OWNCLOUD_LOGLEVEL}" ]] && OWNCLOUD_LOGLEVEL="2"

declare -x OWNCLOUD_MAX_UPLOAD
[[ -z "${OWNCLOUD_MAX_UPLOAD}" ]] && OWNCLOUD_MAX_UPLOAD="20G"

declare -x OWNCLOUD_MAX_EXECUTION_TIME
[[ -z "${OWNCLOUD_MAX_EXECUTION_TIME}" ]] && OWNCLOUD_MAX_EXECUTION_TIME="3600"

declare -x OWNCLOUD_MAX_INPUT_TIME
[[ -z "${OWNCLOUD_MAX_INPUT_TIME}" ]] && OWNCLOUD_MAX_INPUT_TIME="3600"

declare -x OWNCLOUD_SKIP_CHOWN
[[ -z "${OWNCLOUD_SKIP_CHOWN}" ]] && OWNCLOUD_SKIP_CHOWN="false"

declare -x OWNCLOUD_CROND_ENABLED
[[ -z "${OWNCLOUD_CROND_ENABLED}" ]] && OWNCLOUD_CROND_ENABLED="true"

declare -x OWNCLOUD_LOCKING_ENABLED
[[ -z "${OWNCLOUD_LOCKING_ENABLED}" ]] && OWNCLOUD_LOCKING_ENABLED="true"

true
