#!/usr/bin/env bash

declare -x OWNCLOUD_SUB_URL
[[ -z "${OWNCLOUD_SUB_URL}" ]] && OWNCLOUD_SUB_URL="/"

declare -x OWNCLOUD_VOLUME_ROOT
[[ -z "${OWNCLOUD_VOLUME_ROOT}" ]] && OWNCLOUD_VOLUME_ROOT="/mnt/data"

declare -x OWNCLOUD_VOLUME_CONFIG
[[ -z "${OWNCLOUD_VOLUME_CONFIG}" ]] && OWNCLOUD_VOLUME_CONFIG="${OWNCLOUD_VOLUME_ROOT}/config"

declare -x OWNCLOUD_VOLUME_FILES
[[ -z "${OWNCLOUD_VOLUME_FILES}" ]] && OWNCLOUD_VOLUME_FILES="${OWNCLOUD_VOLUME_ROOT}/files"

declare -x OWNCLOUD_VOLUME_APPS
[[ -z "${OWNCLOUD_VOLUME_APPS}" ]] && OWNCLOUD_VOLUME_APPS="${OWNCLOUD_VOLUME_ROOT}/apps"

declare -x OWNCLOUD_VOLUME_SESSIONS
[[ -z "${OWNCLOUD_VOLUME_SESSIONS}" ]] && OWNCLOUD_VOLUME_SESSIONS="${OWNCLOUD_VOLUME_ROOT}/sessions"

declare -x OWNCLOUD_CACHE_PATH
[[ -z "${OWNCLOUD_CACHE_PATH}" ]] && OWNCLOUD_CACHE_PATH=""

true
