#!/usr/bin/env bash

declare -x OWNCLOUD_LOGLEVEL
[[ -z "${OWNCLOUD_LOGLEVEL}" ]] && OWNCLOUD_LOGLEVEL="2"

declare -x OWNCLOUD_LOGSIZE
[[ -z "${OWNCLOUD_LOGSIZE}" ]] && OWNCLOUD_LOGSIZE=""

declare -x OWNCLOUD_ACCESSLOG_LOCATION
[[ -z "${OWNCLOUD_ACCESSLOG_LOCATION}" ]] && OWNCLOUD_ACCESSLOG_LOCATION="/var/log/apache2/access.log"

declare -x OWNCLOUD_ACCESSLOG_DESTINATION
[[ -z "${OWNCLOUD_ACCESSLOG_DESTINATION}" ]] && OWNCLOUD_ACCESSLOG_DESTINATION="stdout"

declare -x OWNCLOUD_ERRORLOG_LOCATION
[[ -z "${OWNCLOUD_ERRORLOG_LOCATION}" ]] && OWNCLOUD_ERRORLOG_LOCATION="/var/log/apache2/error.log"

declare -x OWNCLOUD_ERRORLOG_DESTINATION
[[ -z "${OWNCLOUD_ERRORLOG_DESTINATION}" ]] && OWNCLOUD_ERRORLOG_DESTINATION="stderr"

true
