#!/usr/bin/env bash

declare -x OWNCLOUD_SESSION_HANDLER
[[ -z "${OWNCLOUD_SESSION_HANDLER}" ]] && OWNCLOUD_SESSION_HANDLER="files"

declare -x OWNCLOUD_SESSION_PATH
[[ -z "${OWNCLOUD_SESSION_PATH}" ]] && OWNCLOUD_SESSION_PATH="${OWNCLOUD_VOLUME_SESSIONS}"

true