#!/usr/bin/env bash

declare -x OWNCLOUD_SESSION_SAVE_HANDLER
[[ -z "${OWNCLOUD_SESSION_SAVE_HANDLER}" ]] && OWNCLOUD_SESSION_SAVE_HANDLER="files"

declare -x OWNCLOUD_SESSION_SAVE_PATH
[[ -z "${OWNCLOUD_SESSION_SAVE_PATH}" ]] && OWNCLOUD_SESSION_SAVE_PATH="${OWNCLOUD_VOLUME_SESSIONS}"

true
