#!/usr/bin/env bash

declare -x OWNCLOUD_MARKETPLACE_KEY
[[ -z "${OWNCLOUD_MARKETPLACE_KEY}" ]] && OWNCLOUD_MARKETPLACE_KEY="${OWNCLOUD_MARKETPLACE_APIKEY}"

declare -x OWNCLOUD_MARKETPLACE_CA
[[ -z "${OWNCLOUD_MARKETPLACE_CA}" ]] && OWNCLOUD_MARKETPLACE_CA=""

declare -x OWNCLOUD_APPSTORE_ENABLED
[[ -z "${OWNCLOUD_APPSTORE_ENABLED}" ]] && OWNCLOUD_APPSTORE_ENABLED=""

declare -x OWNCLOUD_APPSTORE_URL
[[ -z "${OWNCLOUD_APPSTORE_URL}" ]] && OWNCLOUD_APPSTORE_URL="${OWNCLOUD_MARKETPLACE_URL}"

true
