#!/usr/bin/env bash

declare -x OWNCLOUD_REDIS_ENABLED
[[ -z "${OWNCLOUD_REDIS_ENABLED}" ]] && OWNCLOUD_REDIS_ENABLED="false"

declare -x OWNCLOUD_REDIS_HOST
[[ -z "${OWNCLOUD_REDIS_HOST}" ]] && OWNCLOUD_REDIS_HOST="redis"

declare -x OWNCLOUD_REDIS_PORT
[[ -z "${OWNCLOUD_REDIS_PORT}" ]] && OWNCLOUD_REDIS_PORT="6379"

declare -x OWNCLOUD_REDIS_DB
[[ -z "${OWNCLOUD_REDIS_DB}" ]] && OWNCLOUD_REDIS_DB=""

declare -x OWNCLOUD_REDIS_PASSWORD
[[ -z "${OWNCLOUD_REDIS_PASSWORD}" ]] && OWNCLOUD_REDIS_PASSWORD=""

declare -x OWNCLOUD_REDIS_TIMEOUT
[[ -z "${OWNCLOUD_REDIS_TIMEOUT}" ]] && OWNCLOUD_REDIS_TIMEOUT=""

true
