#!/usr/bin/env bash

declare -x OWNCLOUD_REDIS_ENABLED
[[ -z "${OWNCLOUD_REDIS_ENABLED}" ]] && OWNCLOUD_REDIS_ENABLED="false"

declare -x OWNCLOUD_REDIS_HOST
[[ -z "${OWNCLOUD_REDIS_HOST}" ]] && OWNCLOUD_REDIS_HOST="redis"

declare -x OWNCLOUD_REDIS_PORT
[[ -z "${OWNCLOUD_REDIS_PORT}" ]] && OWNCLOUD_REDIS_PORT="6379"

declare -x OWNCLOUD_REDIS_DB
[[ -z "${OWNCLOUD_REDIS_DB}" ]] && OWNCLOUD_REDIS_DB=""

declare -x OWNCLOUD_REDIS_PASSWORD
[[ -z "${OWNCLOUD_REDIS_PASSWORD}" ]] && OWNCLOUD_REDIS_PASSWORD=""

declare -x OWNCLOUD_REDIS_TIMEOUT
[[ -z "${OWNCLOUD_REDIS_TIMEOUT}" ]] && OWNCLOUD_REDIS_TIMEOUT=""

declare -x OWNCLOUD_REDIS_STARTUP_TIMEOUT
[[ -z "${OWNCLOUD_REDIS_STARTUP_TIMEOUT}" ]] && OWNCLOUD_REDIS_STARTUP_TIMEOUT="180"

declare -x OWNCLOUD_REDIS_TLS_CAFILE
[[ -z "${OWNCLOUD_REDIS_TLS_CAFILE}" ]] && OWNCLOUD_REDIS_TLS_CAFILE=""

declare -x OWNCLOUD_REDIS_TLS_CAPATH
[[ -z "${OWNCLOUD_REDIS_TLS_CAPATH}" ]] && OWNCLOUD_REDIS_TLS_CAPATH=""

declare -x OWNCLOUD_REDIS_TLS_LOCAL_CERT
[[ -z "${OWNCLOUD_REDIS_TLS_LOCAL_CERT}" ]] && OWNCLOUD_REDIS_TLS_LOCAL_CERT=""

declare -x OWNCLOUD_REDIS_TLS_LOCAL_PK
[[ -z "${OWNCLOUD_REDIS_TLS_LOCAL_PK}" ]] && OWNCLOUD_REDIS_TLS_LOCAL_PK=""

declare -x OWNCLOUD_REDIS_TLS_PASSPHRASE
[[ -z "${OWNCLOUD_REDIS_TLS_PASSPHRASE}" ]] && OWNCLOUD_REDIS_TLS_PASSPHRASE=""

declare -x OWNCLOUD_REDIS_TLS_CIPHERS
[[ -z "${OWNCLOUD_REDIS_TLS_CIPHERS}" ]] && OWNCLOUD_REDIS_TLS_CIPHERS=""

declare -x OWNCLOUD_REDIS_TLS_PEER_NAME
[[ -z "${OWNCLOUD_REDIS_TLS_PEER_NAME}" ]] && OWNCLOUD_REDIS_TLS_PEER_NAME=""

declare -x OWNCLOUD_REDIS_TLS_VERIFY_PEER
[[ -z "${OWNCLOUD_REDIS_TLS_VERIFY_PEER}" ]] && OWNCLOUD_REDIS_TLS_VERIFY_PEER=""

declare -x OWNCLOUD_REDIS_TLS_VERIFY_PEER_NAME
[[ -z "${OWNCLOUD_REDIS_TLS_VERIFY_PEER_NAME}" ]] && OWNCLOUD_REDIS_TLS_VERIFY_PEER_NAME=""

declare -x OWNCLOUD_REDIS_TLS_ALLOW_SELF_SIGNED
[[ -z "${OWNCLOUD_REDIS_TLS_ALLOW_SELF_SIGNED}" ]] && OWNCLOUD_REDIS_TLS_ALLOW_SELF_SIGNED=""

true
