#!/usr/bin/env bash

declare -x OWNCLOUD_MAIL_DOMAIN
[[ -z "${OWNCLOUD_MAIL_DOMAIN}" ]] && OWNCLOUD_MAIL_DOMAIN=""

declare -x OWNCLOUD_MAIL_FROM_ADDRESS
[[ -z "${OWNCLOUD_MAIL_FROM_ADDRESS}" ]] && OWNCLOUD_MAIL_FROM_ADDRESS=""

declare -x OWNCLOUD_MAIL_SMTP_DEBUG
[[ -z "${OWNCLOUD_MAIL_SMTP_DEBUG}" ]] && OWNCLOUD_MAIL_SMTP_DEBUG=""

declare -x OWNCLOUD_MAIL_SMTP_MODE
[[ -z "${OWNCLOUD_MAIL_SMTP_MODE}" ]] && OWNCLOUD_MAIL_SMTP_MODE=""

declare -x OWNCLOUD_MAIL_SMTP_HOST
[[ -z "${OWNCLOUD_MAIL_SMTP_HOST}" ]] && OWNCLOUD_MAIL_SMTP_HOST=""

declare -x OWNCLOUD_MAIL_SMTP_PORT
[[ -z "${OWNCLOUD_MAIL_SMTP_PORT}" ]] && OWNCLOUD_MAIL_SMTP_PORT=""

declare -x OWNCLOUD_MAIL_SMTP_TIMEOUT
[[ -z "${OWNCLOUD_MAIL_SMTP_TIMEOUT}" ]] && OWNCLOUD_MAIL_SMTP_TIMEOUT=""

declare -x OWNCLOUD_MAIL_SMTP_SECURE
[[ -z "${OWNCLOUD_MAIL_SMTP_SECURE}" ]] && OWNCLOUD_MAIL_SMTP_SECURE=""

declare -x OWNCLOUD_MAIL_SMTP_AUTH
[[ -z "${OWNCLOUD_MAIL_SMTP_AUTH}" ]] && OWNCLOUD_MAIL_SMTP_AUTH=""

declare -x OWNCLOUD_MAIL_SMTP_AUTH_TYPE
[[ -z "${OWNCLOUD_MAIL_SMTP_AUTH_TYPE}" ]] && OWNCLOUD_MAIL_SMTP_AUTH_TYPE=""

declare -x OWNCLOUD_MAIL_SMTP_NAME
[[ -z "${OWNCLOUD_MAIL_SMTP_NAME}" ]] && OWNCLOUD_MAIL_SMTP_NAME=""

declare -x OWNCLOUD_MAIL_SMTP_PASSWORD
[[ -z "${OWNCLOUD_MAIL_SMTP_PASSWORD}" ]] && OWNCLOUD_MAIL_SMTP_PASSWORD=""

true
