FROM owncloud/php:24.04@sha256:5d7d64f1359abe873bea2db066411f56e835a74637b3f0653f96db5e6b59211c

LABEL maintainer="ownCloud GmbH <devops@owncloud.com>" \
  org.opencontainers.image.authors="ownCloud DevOps <devops@owncloud.com>" \
  org.opencontainers.image.title="ownCloud Base" \
  org.opencontainers.image.url="https://hub.docker.com/r/owncloud/base" \
  org.opencontainers.image.source="https://github.com/owncloud-docker/base" \
  org.opencontainers.image.documentation="https://github.com/owncloud-docker/base"

RUN mkdir -p /home/owncloud /var/www/owncloud /mnt/data/files /mnt/data/config /mnt/data/certs /mnt/data/sessions && \
  chown -R www-data:root /var/www/owncloud /mnt/data && \
  chgrp root /home/owncloud /var/run /var/lock/apache2 /var/run/apache2 /etc/environment && \
  chmod g+w /home/owncloud /var/run /var/lock/apache2 /var/run/apache2 /etc/environment && \
  chsh -s /bin/bash www-data

ADD overlay /
WORKDIR /var/www/owncloud

RUN chgrp root /etc/apache2/sites-enabled/default.conf /etc/php/8.3/mods-available/owncloud.ini && \
  chmod g+w /etc/apache2/sites-enabled/default.conf /etc/php/8.3/mods-available/owncloud.ini

VOLUME ["/mnt/data"]
EXPOSE 8080

ENTRYPOINT ["/usr/bin/entrypoint"]
CMD ["/usr/bin/owncloud", "server"]
