name: Docker CI

on:
  push:
    branches: [master]
    tags: ["*"]
  pull_request:
  schedule:
    - cron: 0 0 * * 0

jobs:
  lint:
    uses: owncloud-docker/ubuntu/.github/workflows/lint-editorconfig.yml@master

  build:
    name: build (${{ matrix.version.value }})
    needs: lint
    uses: owncloud-docker/ubuntu/.github/workflows/docker-build.yml@master
    with:
      docker-repo-name: owncloud/${{ github.event.repository.name }}
      docker-tag: ${{ matrix.version.value }}
      docker-context: v${{ matrix.version.value }}
      docker-file: v${{ matrix.version.value }}/Dockerfile.multiarch
      docker-hub-username: ${{ vars.DOCKERHUB_USERNAME }}
      smoke-test-cmd: "php -r \"echo 'OK';\" | grep -q OK"
      push: ${{ github.ref == 'refs/heads/master' }}
    secrets:
      docker-hub-password: ${{ secrets.DOCKERHUB_TOKEN }}

    strategy:
      matrix:
        version:
          - value: "22.04"
          - value: "24.04"

  update-docker-hub-description:
    needs: build
    if: github.ref == 'refs/heads/master'
    uses: owncloud-docker/ubuntu/.github/workflows/docker-hub-desc.yml@master
    with:
      docker-repo-name: owncloud/${{ github.event.repository.name }}
      docker-repo-description: ownCloud server base image
      docker-hub-username: ${{ vars.DOCKERHUB_USERNAME }}
    secrets:
      docker-hub-password: ${{ secrets.DOCKERHUB_TOKEN }}
